source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '8.0'

target ‘YelpBetterBookmarks’ do
  pod 'Yoga', :path => '../node_modules/react-native/ReactCommon/yoga/Yoga.podspec'
  pod 'React', path: '../node_modules/react-native', :subspecs => [
    'Core',
    'RCTActionSheet',
    'RCTAnimation',
    'RCTGeolocation',
    'RCTImage',
    'RCTLinkingIOS',
    'RCTNetwork',
    'RCTSettings',
    'RCTText',
    'RCTVibration',
    'RCTWebSocket'
  ]

  pod 'GoogleMaps'
  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'
end
